//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LudothekWeb_M133.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ausleihe
    {
        public System.Guid AusleiheKeyGUID { get; set; }
        public System.DateTime Startdatum { get; set; }
        public System.DateTime Enddatum { get; set; }
        public System.Guid FK_Kunde { get; set; }
        public System.Guid FK_Spiel1 { get; set; }
        public Nullable<System.Guid> FK_Spiel2 { get; set; }
        public Nullable<System.Guid> FK_Spiel3 { get; set; }
    
        public virtual Kunde Kunde { get; set; }
        public virtual Spiel Spiel { get; set; }
        public virtual Spiel Spiel1 { get; set; }
        public virtual Spiel Spiel2 { get; set; }
    }
}
