//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LudothekWeb_M133.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestellung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bestellung()
        {
            this.SpielBestellung = new HashSet<SpielBestellung>();
        }
    
        public int Referenznummer { get; set; }
        public System.DateTime Datum { get; set; }
        public int FK_Mitarbeiter { get; set; }
        public System.Guid FK_Filiale { get; set; }
        public System.Guid FK_Verlag { get; set; }
    
        public virtual Filiale Filiale { get; set; }
        public virtual Mitarbeiter Mitarbeiter { get; set; }
        public virtual Verlag Verlag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpielBestellung> SpielBestellung { get; set; }
    }
}
