//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ludothek.Storage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpielBestellung
    {
        public System.Guid SpielBestellungKeyGUID { get; set; }
        public int FK_Bestellung { get; set; }
        public System.Guid FK_Spiel { get; set; }
    
        public virtual Bestellung Bestellung { get; set; }
        public virtual Spiel Spiel { get; set; }
    }
}
